dist: trusty
sudo: required
addons:
  apt:
    packages:
    - qemu
    - qemu-user-static
    - binfmt-support
    - parted
    - wget
    - dosfstools
    - zip
install: travis_wait
script:
- sudo bash ./create-image
- travis_wait 30 xz -z discordAnnoucer.img -c > discordAnnouncer.img.xz
- zip discordAnnoucer.img.zip discordAnnoucer.img
deploy:
  provider: releases
  api_key:
    secure: ACRUh1+ZZcdp7g05gQlr3O76hScfV3fVpauikVB6LuVnR51LszBQYcLCWqhKHpuOU7Hav7iSzpg0CU9cp1TOYdJYxZy9I3TYYvFyD6ljEqDLDllo+QNmFi3gGZ9OXSPRGh0WKT1/p0rCznFTP2VV0SElOOwK9JSbFWOw7sG/1aRO0+rZBIWm/hgrMoNgpCfKWWzSJ4h1nhfAIeTT9XMaBERlHTd3nqst2PLjf9dglw5zRzssUHT3QYZUreogWVvDoe1HdPzNv4iNidCjYxsPa/dttChtJZZecPeBE+3DCjHNeXwW0oJWOshGGtWXYvrV1dzeOUObntVw2M7YcWupFc+RogJL/p1o0QvOusB5HzCB9WDWqZ5Xhe+1BXT0UiT1J05pGJiA9ZTZ2DeXby24vyi2bBWm1UCF/7NW33D3xuUdF/tqJcQxaBRywi+JrCCf7fjv+78e5qQK+JrLJ+DQOsGhDOWbl9LKcbDhMR9jnsBo+STBodSAYYEiEdkbepfeNhMeE1LRASar+lqOniW9HOxCtdIcrCuD7M8B7hYyqB8WhegsaZ1uclLQOWu9iuu8HYaXZUKFyNH6JAzk5K83QUUj3Dz8vrJdpfQjG5q7LIrizDwRP9vuZWY+UxerA3rhmPeqbMvci1nWib7LUByofDI8H6Lejg91OTRv0vHq6xU=
  file:
  - discordAnnoucer.img.xz
  - discordAnnoucer.img.zip
  skip_cleanup: true
  true:
    repo: subzerodev/WeebBot
    tags: true
