dist: trusty
sudo: required
addons:
  apt:
    packages:
    - qemu
    - qemu-user-static
    - binfmt-support
    - parted
    - wget
    - dosfstools
    - zip
install: travis_wait
script:
- sudo bash ./create-image
- "travis_wait 30 sleep 1800 &"
- xz -z discordAnnoucer.img -c > discordAnnoucer.img.xz
- zip discordAnnoucer.img.zip discordAnnoucer.img
deploy:
  provider: releases
  api_key: 
    secure: FdLv3MlGPl5xsBUB30mUwlH9DXtK7TFiNB9ZwfDe5OACzhA5t5VFXkKzyRHY1zKgOdu4QcXYw488SkPL14o7liZXQboaxm8Ftd9cvP3h2B5C619CBw8wCM89Nxfza2YFmYYs3FrLDjWl3bkdT5OkaMSIWJ85EJ6Ev012ice9FTYyJ05lNoPXeEbjfIjyCTuMjQ20Mh+11IcGveTGg0RoCt/H6XtrQTRlAQjJU1BboeMxwHaj3z+VEcrzMkGwu2v2u6CQe1XwgMpp6/wZJMKQjs0iqZkypFSF+YKLfDWE3FD2y5pExwnivLgHxu2h1GGXWyOnQ6uB1zyZRbZOfB1uSGocv35xCYt6FhHpdyBANg8SCRa7UBamj4VXHywjl6zo6ZTo2LBIj6k1t2u18b7SN4vEXq/h77Qo0QTvdETKKYiVmnOVUFyQHLM4WsqrF7SSGeAJfTyuVKH9RQVFmTsB805EQZoAa3MlWGnVld2KofESaY3z5TI0MVVNAey4p7eKCuKCZntGY7fP6mGmsSpeLzY3bNHZP3ln1V1sjlNdtY42nzBKBvJX1kL7n86r1OxUmlLeXMQbMQNktm/iws9C9k/gzmA7T63l86g0MYJRPEpB0dAmGXdZQLIM8tEC7Z3ciVymQJ1E92YJdsSdEZ/s+t5AtcIZH8WIr7+erPOeFy4=
  file:
  - discordAnnoucer.img.xz
  - discordAnnoucer.img.zip
  skip_cleanup: true
  on:
    branch: main
    repo: subzerodev/WeebBot
    tags: true
