#!/bin/zsh

ls /home/discordannoucer/ | grep WeebBot > /dev/null

# check output of the previous command
if [ $? -eq 0 ]
then
     echo -e "Found file"
     git pull https://github.com/subzerodev/WeebBot.git
else
     echo -e "File is not in there"
     git clone https://github.com/subzerodev/WeebBot.git
fi


# Check for the file
ls /boot/ | grep apikey > /dev/null

# check output of the previous command
if [ $? -eq 0 ]
then
     echo -e "Found file"
    mv /boot/apikey /home/discordannoucer/WeebBot/.env
else
     echo -e "File is not in there"
fi

# Check for the file
ls /boot/ | grep wifikey > /dev/null

# check output of the previous command
if [ $? -eq 0 ]
then
     echo -e "Found file"
    mv /boot/wifikey /etc/netctl/wlan0-network
else
     echo -e "File is not in there"
fi

netctl reenable wlan0-network

tmux new -s discord -d

tmux send-keys -t 'discord' 'python3 /home/discordannoucer/WeebBot/indicator.py' C-m
